spring.application.name=demo
# server.port=8081
spring.datasource.url=jdbc:postgresql://localhost:5432/Nutricion
spring.datasource.username=postgres
spring.datasource.password=AlumnoDAM

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
rickandmorty.url=https://rickandmortyapi.com/api/character
spring.data.redis.url=
    redis://default:HMe1QfiR1JroZ1iQMJGhK3xBxz4rxOQb@redis-11803.c13.us-east-1-3.ec2.cloud.redislabs.com:11803